
# code: language=Dockerfile

FROM python:3.9.6-slim-buster@sha256:28bed4c51c3b531159d8affc0225701edb16a7deacfdfdfb220a944405c39314 as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install \
    git \
    wget \
    curl \
    unzip \
    gpg \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true

# Installing Google Chrome browser
RUN \
  curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add && \
  echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
  apt-get -y update && \
  apt-get -y install \
    google-chrome-stable \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true

RUN pip install --no-cache-dir selenium requests chromedriver-autoinstaller

COPY docker/wait-for-it.sh \
  docker/entrypoint-integration-tests.sh \
  /

COPY tests/ ./tests/

RUN chmod -R 0777 /app

# These 2 lines are needed for the chromium driver 
RUN chmod -R ugo+w /usr/local/lib/python3.8/site-packages
RUN mkdir /.local
RUN chmod -R ugo+w /.local

USER 1001
ENV \
  DD_ADMIN_USER=admin \
  DD_ADMIN_PASSWORD='' \
  DD_BASE_URL="http://localhost:8080/"
CMD ["/entrypoint-integration-tests.sh"]
