# Generated by Django 2.2.12 on 2020-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0035_auto_20200412_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='product',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Product'),
        ),
        migrations.AddConstraint(
            model_name='notifications',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='notifications_user_product'),
        ),
    ]
