# Generated by Django 5.1.13 on 2025-11-01 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0247_findingreviewers_findingreviewersevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(db_index=True, max_length=255, verbose_name='object pk')),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='object id')),
                ('object_repr', models.TextField(verbose_name='object representation')),
                ('serialized_data', models.JSONField(null=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'create'), (1, 'update'), (2, 'delete'), (3, 'access')], db_index=True, verbose_name='action')),
                ('changes_text', models.TextField(blank=True, verbose_name='change message')),
                ('changes', models.JSONField(null=True, verbose_name='change message')),
                ('cid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Correlation ID')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('remote_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='remote port')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='additional data')),
                ('actor_email', models.CharField(blank=True, max_length=254, null=True, verbose_name='actor email')),
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'db_table': 'auditlog_logentry',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'managed': False,
            },
        ),
    ]
