apiVersion: v1
<<<<<<< HEAD
appVersion: "1.11.0-dev"
=======
appVersion: "1.10.3"
>>>>>>> Update versions in application files
description: A Helm chart for Kubernetes to installs DefectDojo
name: defectdojo
version: 1.4.0
icon: https://www.defectdojo.org/img/favicon.ico
