baseURL = "http://example.org/"
languageCode = "en-us"
title = "DefectDojo Documentation"
theme = "learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/DefectDojo/django-DefectDojo"
weight = 10