name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev
      - bugfix
      - release/**
      - hotfix/**

jobs:
  build-docker-containers:
    strategy:
        matrix:
          runs-on: ["ubuntu-latest", "ubuntu-22.04-arm"]
    uses: ./.github/workflows/build-docker-images-for-testing.yml
    secrets: inherit
    with:
      runs-on: '["${{ matrix.runs-on }}"]'

  test-rest-framework:
    strategy:
        matrix:
          runs-on: ["ubuntu-latest", "ubuntu-22.04-arm"]
    needs: build-docker-containers
    uses: ./.github/workflows/rest-framework-tests.yml
    secrets: inherit
    with:
      runs-on: '["${{ matrix.runs-on }}"]'

  # only run integration tests on ubuntu-latest (x64)
  test-user-interface:
    needs: build-docker-containers
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  # only run k8s tests on ubuntu-latest (x64)
  test-k8s:
    needs: build-docker-containers
    uses: ./.github/workflows/k8s-tests.yml
    secrets: inherit
